name: Publish to PyPI

on:
  push:
    tags:
      - v*

jobs:
  build_wheels:
    if: github.repository_owner == 'michalsta'
    uses: ./.github/workflows/build_wheels.yml

  tests:
    if: github.repository_owner == 'michalsta'
    uses: ./.github/workflows/run_tests.yml

  upload_pypi:
    name: Upload to PyPI
    if: github.repository_owner == 'michalsta'
    needs: [build_wheels, tests]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Download artifacts from Build workflow
        uses: actions/download-artifact@v5
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        # To test uploads to TestPyPI, uncomment the following:
        # with:
        #   repository-url: https://test.pypi.org/legacy/
